### ISSUE TITLE
Popup opens on wrong monitor

### ISSUE THREAD

**Issue by Daki0082** [emvaized/open-in-popup-window-extension#8]
I have two monitors. When Firefox is on the primary monitor, it works just fine, but when Firefox is on the secondary monitor, the popup always opens on the primary monitor

**Comment by emvaized** [comment]
Thanks for report! Unfortunately, I don't have multi-monitor setup to test. 

1) Is your secondary monitor located to the left or to the right of the primary monitor? 
2) What happens if you change popup location to "Bottom left" or "Bottom right"?

**Comment by Daki0082** [comment]
1. My Primary monitor is on the right, and my **secondary monitor** is on the **left**.

2. If I change the location to "Bottom left", the popup window opens in the bottom left corner of my primary monitor. If I change it to "Bottom right", the popup window opens on the bottom left side of my primary monitor.



3. If I change it to "Mouse cursor position" it always opens on the very left side of my primary monitor

**Comment by emvaized** [comment]
Hm, that's weird. In given setup, at least the "Bottom left" option should work correctly and open on the secondary monitor, as we're just padding `0` as `dx` coordinate with this setting. 

Maybe some window manager on your computer overrides the screen placement and forces new windows to open on primary monitor?

**Comment by Daki0082** [comment]
No, I don't have any window manager installed

**Comment by emvaized** [comment]
Could you try to install this test version and then try again with the "Bottom left" position settings?
[test.zip](https://github.com/user-attachments/files/17002967/test.zip) 

I can provide detailed instructions on how to install it if you specify which browser are you using.

**Comment by Daki0082** [comment]
I installed it, but I think you sent me the wrong extension. You sent me "Linkover", not "Open in popup window"

**Comment by emvaized** [comment]
Oops! My bad. 
Here's the correct archive: 
[test_open_in_popup_window.zip](https://github.com/user-attachments/files/17002979/test_open_in_popup_window.zip)

Here I disabled the code which checks if opened window is going to be rendered off-screen, and shifts it to fit to the screen. I have a suggestion that this code causes wrong behavior on multi-screen setup.

**Comment by Daki0082** [comment]
Yes, now it works

**Comment by emvaized** [comment]
Does it work with all tested options for popup placement, both "mouse position" and "bottom left/right" corners?

**Comment by Daki0082** [comment]
Sorry, I forgot to test the other options.

Only "Mouse cursor position" and "Near mouse cursor" work, the other options still open on the primary monitor

**Comment by emvaized** [comment]
I see. It's very confusing, as "Top left" and "Bottom left" options just pass `0px` as `dx` coordinate for the new window. And in multi-monitor setup the very left edge of your combined screen space should be considered as `dx = 0`. 

I have no idea why in your case the left side of the secondary monitor is actually considered `0` – which probably means that left side of the secondary monitor is `-n px`)? 

Probably I should create a release with detailed console logging on each open of the popup window, and then we should examine your console output and actual screen coordinates

**Comment by emvaized** [comment]
Please try this version, and let me know what is the console output with both `Bottom left` and `Mouse position` options enabled. 
[test_logging.zip](https://github.com/user-attachments/files/17003099/test_logging.zip) 

Let me know if you need help on where to find the console output of the background sript.

**Comment by Daki0082** [comment]
Where can I find the console output?

**Comment by Daki0082** [comment]
(The popup windows now open on the primary monitor again when using the mouse options, idk if it's intended or not)

Mouse cursor position:

![grafik](https://github.com/user-attachments/assets/3d8a6f35-78d9-4018-a357-f3d78a591ecd)



Bottom Left:

![grafik](https://github.com/user-attachments/assets/eaf5f935-4c0d-4783-8901-c19c8552d2a7)

**Comment by emvaized** [comment]
Thanks! As I suggested, your secondary screen is treated as a negative space for some reason. I can't think of a quick solution right now, but I will investigate this problem.

**Comment by Daki0082** [comment]
Okay, thank you!

**Comment by emvaized** [comment]
Could you please open dev tools (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> on Windows), switch to "Console", paste `window.screen.availLeft` and hit <kbd>Enter</kbd>? What will it return when browser is on primary screen, and when it is on a secondary screen?

**Comment by Daki0082** [comment]
Primary screen: 0

Secondary screen: -1920

**Comment by emvaized** [comment]
Okay, thanks! 
Another test build for you to try: 
[test3.zip](https://github.com/user-attachments/files/17004406/test3.zip)

**Comment by Daki0082** [comment]
I'll try it tomorrow

**Comment by Daki0082** [comment]
I tried it, but the popup windows still open on the primary monitor, no matter which location I choose

**Comment by emvaized** [comment]
I see. And what does it output in the dev console, if you enable the new "Debug mode" option in the setting?

**Comment by Daki0082** [comment]
Mouse Cursor Position:

Sending message to bg script:  
Object { mouseX: -1412, mouseY: 889, elementHeight: 16, elementWidth: 163, availHeight: 1032, availWidth: 1920, selectedText: "", availLeft: -1920, type: "shiftClick", nodeName: "A", … }


Bottom Left:

Sending message to bg script:  
Object { mouseX: -1386, mouseY: 889, elementHeight: 16, elementWidth: 163, availHeight: 1032, availWidth: 1920, selectedText: "", availLeft: -1920, type: "shiftClick", nodeName: "A", … }

**Comment by emvaized** [comment]
That's weird... Could you please try this build, and if no option still works, post the output of the **background script** console with "Debug mode" option enabled (the one which can be accessed on `about:debug` page by clicking the "Inspect" button?

[test4.zip](https://github.com/user-attachments/files/17006754/test4.zip)

**Comment by Daki0082** [comment]
No option worked, here is the console output:

Mouse Cursor Position:
![grafik](https://github.com/user-attachments/assets/6f65ae5b-8bbb-47fe-a56d-a9616262f7cb)

Bottom Left:
![grafik](https://github.com/user-attachments/assets/176e0c3a-4cb4-4adb-9f9d-99bb8bfd7314)

**Comment by emvaized** [comment]
This is the output when you open popup when browser is on the secondary screen on the left, is it correct?

**Comment by Daki0082** [comment]
Yes, that is correct

**Comment by emvaized** [comment]
Please also share the output from the page developer console, which could be opened by <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> on any page (when browser is on the secondary screen)

**Comment by Daki0082** [comment]
Mouse Cursor Position:
![grafik](https://github.com/user-attachments/assets/a6241ee8-5142-4b23-83aa-f85f93389086)


Bottom Left:
![grafik](https://github.com/user-attachments/assets/e159040b-083d-49d3-ac60-0b876a715492)

**Comment by emvaized** [comment]
Okay, then I think this one might work just fine: 
[test5.zip](https://github.com/user-attachments/files/17007302/test5.zip)

**Comment by Daki0082** [comment]
All the options work, except for top right

**Comment by emvaized** [comment]
Great! Does it work on both primary and secondary monitors?

**Comment by Daki0082** [comment]
Yes, everything works. Only Top Right is broken on secondary monitor

**Comment by emvaized** [comment]
OK, great! Then I'll fix the "top right" option and release an update with multi-monitor support. Thanks for help with debugging! 👍

**Comment by Daki0082** [comment]
Great! You're welcome!

**Comment by emvaized** [comment]
I just pushed new update `v0.3.2` which includes the fix 🎉
